# Лабораторна робота №1 - Базове знайомство з бібліотекою NumPy
## ІП-13 Ал Хадам Мурат Резгович

# Завдання до лабораторної роботи:
## Створити програму, яка:
1. Генерує випадкові і невипадкові масиви різними способами,зазначеними в теоретичних відомостях.
2. Демонструє звернення до елементів масиву за допомогою індексів, в тому числі від’ємних; виділення підмасивів як одновимірних, так і багатовимірних масивів.
3. Демонструє основні арифметичні операції над масивами, а також роботу методів reduce, accumulate, outer.
4. Вираховує статистичні характеристики, а саме, мінімальне імаксимальне значення, вибіркові середнє, дисперсію,середньоквадратичне відхилення, медіану та 25 та 75 персентилі, величини ширина пелюстки (petal_width) з набору даних щодо квіток ірису (iris.csv).

### Завдання 1
1. Створення масиву, елементи якого починаються з 15, закінчуються 50 з кроком 3

In [1]:
import numpy as np


arr = np.arange(15, 50, 3)
arr

array([15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

2. Масив з деcяти цілочислених одиниць

In [2]:
arr = np.ones(10, dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

3. Масив двовимірний, кожний рядок якого містить пять нулів, тип даних з плаваючою точкою

In [3]:
arr = np.zeros ((2, 5), dtype=float)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4. Масив з семи значень, розміщених рівномірно між 50 та 100.

In [4]:
arr = np.linspace(50, 100, 7)
arr

array([ 50.        ,  58.33333333,  66.66666667,  75.        ,
        83.33333333,  91.66666667, 100.        ])

5. Масив 5х6 з рівномірно розподілених випадкових чисел від 0 до 1.

In [5]:
arr = np.random.random((5, 6))
arr

array([[0.87071145, 0.00201989, 0.85616146, 0.4449738 , 0.09100902,
        0.22655825],
       [0.74049194, 0.84219684, 0.11767975, 0.66017374, 0.49888058,
        0.68420892],
       [0.93984614, 0.56456155, 0.52035642, 0.84358127, 0.13163558,
        0.33692838],
       [0.19554537, 0.35017846, 0.6293856 , 0.09270545, 0.86069625,
        0.49025246],
       [0.50198521, 0.5412618 , 0.73282993, 0.77690621, 0.76138532,
        0.42816256]])

6. Масив 5х5 випадкових цілих чисел від 1 до 10.

In [6]:
arr = np.random.randint(1, 10, (5, 5))
arr

array([[2, 3, 8, 8, 4],
       [3, 6, 4, 2, 5],
       [9, 6, 6, 5, 6],
       [3, 1, 5, 2, 4],
       [8, 4, 8, 2, 1]])

7. Порожній масив з 7 елементів. Насправді, його елементами буде випадковий вміст комірок пам’яті

In [7]:
arr = np.empty(7)
arr

array([ 50.        ,  58.33333333,  66.66666667,  75.        ,
        83.33333333,  91.66666667, 100.        ])

### Завдання 2

In [8]:
arr = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
arr.shape

(3, 3)

Демонструє звернення до елементів масиву за допомогою індексів, в тому числі від’ємних;

In [9]:
print(arr[1])
print(arr[-1])
print(arr[0, 0])

[4 5 6]
[7 8 9]
1


Демонструє виділення підмасивів як одновимірних, так і багатовимірних масивів.

In [10]:
print(arr[1:])
print(arr[1:, :2])

[[4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]


### Завдання №3

In [11]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

Демонструє основні арифметичні операції над масивами

In [12]:
a += 3
print(a)
a -= 10
print(a)
a *= 2
print(a)
a /= 2
print(a)
a = a ** 2
print(a)
a %= 19
print(a)
a = np.negative(a)
print(a)

[4. 4. 4. 4.]
[-6. -6. -6. -6.]
[-12. -12. -12. -12.]
[-6. -6. -6. -6.]
[36. 36. 36. 36.]
[17. 17. 17. 17.]
[-17. -17. -17. -17.]


A також роботу методів reduce, accumulate, outer.

In [13]:
a = np.arange(0, 6)
print(a)
np.add.reduce(a)

[0 1 2 3 4 5]


15

In [14]:
np.add.accumulate(a)

array([ 0,  1,  3,  6, 10, 15])

In [15]:
a = np.arange(1, 10)
print(a)
np.multiply.outer(a, a)

[1 2 3 4 5 6 7 8 9]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

### Завдання №4
Вираховує статистичні характеристики, а саме, мінімальне і максимальне значення, вибіркові середнє, дисперсію, середньоквадратичне відхилення, медіану та 25 та 75 персентилі, величини ширина пелюстки (petal_width) з набору даних щодо квіток ірису (iris.csv).

In [16]:
import pandas as pd


iris = pd.read_csv('iris.csv')
petal = np.array(iris['petal_width'])
iris

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [17]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [18]:
print('Min value of petal_length:', np.min(petal))
print('Max value of petal_length:', np.max(petal))

print('\nSum of petal_length values:', np.sum(petal))
print('Mean value of petal_length:', np.mean(petal))

print('\nStandard deviation of petal_length:', np.std(petal))
print('Variance of petal_length:', np.var(petal))

print('\nThe 25th percentile of petal_length:', np.percentile(petal, 25))
print('Median value of petal_length:', np.median(petal))
print('The 75th percentile of petal_length:', np.percentile(petal, 75))

Min value of petal_length: 0.1
Max value of petal_length: 2.5

Sum of petal_length values: 179.8
Mean value of petal_length: 1.1986666666666668

Standard deviation of petal_length: 0.7606126185881716
Variance of petal_length: 0.5785315555555555

The 25th percentile of petal_length: 0.3
Median value of petal_length: 1.3
The 75th percentile of petal_length: 1.8
